export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";

export const ADD_PRODUCT_SAGA = "ADD_PRODUCT_SAGA";
export const FETCH_PRODUCT_SAGA = "FETCH_PRODUCT_SAGA";
export const DELETE_PRODUCT_SAGA = "DELETE_PRODUCT_SAGA";
export const UPDATE_PRODUCT_SAGA = "UPDATE_PRODUCT_SAGA";
export const SEARCH_PRODUCT_SAGA = "SEARCH_PRODUCT_SAGA";
export const FETCH_PRODUCT_BY_ID_SAGA = "FETCH_PRODUCT_BY_ID_SAGA";

export const EMPTY_CART = "EMPTY_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export const EMPTY_WISHLIST = "EMPTY_WISHLIST";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
